### ISSUE TITLE
xud-simnet-install

### ISSUE THREAD

**Issue by offerm** [ExchangeUnion/xud-simnet#2]
fix the errors from npm i

**Comment by offerm** [comment]
hiden now

**Comment by erkarl** [comment]
`sudo apt install -y python` as an additional dependency should solve it.

**Comment by offerm** [comment]
on mac:

```
admins-MacBook-Pro-2:xud-simnet admin$ sudo apt install -y python
Password:
Unable to locate an executable at "/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/apt" (-1)
```

on linux 
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python is already the newest version (2.7.13-2).
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.
```


but `npm i`
gives compile errors:
```
 secp256k1@3.5.0 rebuild /home/offerm/xud-simnet/xud/node_modules/secp256k1
> node-gyp rebuild
make: Entering directory '/home/offerm/xud-simnet/xud/node_modules/secp256k1/build'
  CXX(target) Release/obj.target/secp256k1/src/addon.o
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:203,
                 from ../src/addon.cc:2:
../../nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::StringObject>::return_t Nan::imp::Factory<v8::StringObject>::New(v8::Local<v8::String
>)’:
../../nan/nan_implementation_12_inl.h:337:37: warning: ‘static v8::Local<v8::Value> v8::StringObject::New(v8::Local<v8::String>)’ is deprecated: Use Isolate* version [-Wdeprecated-decl
arations]
   return v8::StringObject::New(value).As<v8::StringObject>();
                                     ^
In file included from /home/offerm/.node-gyp/10.12.0/include/node/v8.h:26:0,
                 from /home/offerm/.node-gyp/10.12.0/include/node/node.h:63,
                 from ../src/addon.cc:1:
/home/offerm/.node-gyp/10.12.0/include/node/v8.h:5053:37: note: declared here
                 static Local<Value> New(Local<String> value));
                                     ^
/home/offerm/.node-gyp/10.12.0/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/addon.cc:2:0:
../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’:
../../nan/nan.h:840:60: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated: Use 
MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, func, argc, argv);
                                                            ^
In file included from ../src/addon.cc:1:0:
```

**Comment by erkarl** [comment]
Python 2.7 should be installed by default on OSX. A clean ubuntu install doesn't have one, but looks like your environment has it installed.

The output for npm i looks correct. It's not failing the build, rather than showing deprecation warnings.

**Comment by offerm** [comment]
@erkarl is there a reason not to close this?

What do you suggest as `missing`?

**Comment by erkarl** [comment]
@offerm I'm getting the following output on a fresh ubuntu 18.04.1 server when installing xud:

```
> secp256k1@3.5.0 rebuild /home/ar/xud-simnet/xud/node_modules/secp256k1
> node-gyp rebuild

gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/home/ar/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/home/ar/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/home/ar/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/home/ar/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /home/ar/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /home/ar/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /home/ar/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
gyp ERR! System Linux 4.15.0-36-generic
gyp ERR! command "/home/ar/.nvm/versions/node/v10.13.0/bin/node" "/home/ar/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ar/xud-simnet/xud/node_modules/secp256k1
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! secp256k1@3.5.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the secp256k1@3.5.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ar/.npm/_logs/2018-11-02T15_54_56_381Z-debug.log
```

I'd recommend we add `python2.7` as a dependency under the `pre-requisites` section of the guide.

**Comment by kilrau** [comment]
done
