### ISSUE TITLE
ltcd runtime error

### ISSUE THREAD

**Issue by moshababo** [ExchangeUnion/xud-simnet#9]
```
Moshes-MacBook-Pro-3:xud-simnet moshe$ go version
go version go1.10 darwin/amd64
```

```
Moshes-MacBook-Pro-3:~ moshe$ ltcd --simnet --txindex --datadir=./data --logdir=./logs --addpeer=35.231.222.142:19555 --rpcuser=xu --rpcpass=xu --rpclisten=127.0.0.1:19556 
2018-11-03 13:58:54.015 [INF] BTCD: Version 0.12.0-beta
2018-11-03 13:58:54.016 [INF] BTCD: Loading block database from 'data/simnet/blocks_ffldb'
2018-11-03 13:58:54.026 [INF] BTCD: Block database loaded
2018-11-03 13:58:54.037 [INF] INDX: Transaction index is enabled
2018-11-03 13:58:54.037 [INF] INDX: cf index is enabled
2018-11-03 13:58:54.037 [INF] CHAN: Loading block index.  This might take a while...
2018-11-03 13:58:54.038 [INF] BTCD: Gracefully shutting down the database...
2018-11-03 13:58:54.039 [INF] BTCD: Shutdown complete
panic: runtime error: slice bounds out of range [recovered]
	panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/ltcsuite/ltcd/database/ffldb.rollbackOnPanic(0xc4200d01b0)
	/Users/moshe/xud-simnet/go/src/github.com/ltcsuite/ltcd/database/ffldb/db.go:1889 +0x77
panic(0x1598960, 0x1aaa090)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/panic.go:505 +0x229
github.com/ltcsuite/ltcd/database/ffldb.(*transaction).FetchBlockHeader(0xc4200d01b0, 0xc4204bc160, 0x68, 0x20, 0xc4204bc140, 0xc420460040, 0xc4204bc160)
	/Users/moshe/xud-simnet/go/src/github.com/ltcsuite/ltcd/database/ffldb/db.go:1278 +0x2bc
github.com/ltcsuite/ltcd/blockchain.dbFetchHeaderByHash(0x17f7440, 0xc4200d01b0, 0xc4204bc160, 0xc4204bc160, 0x0, 0x0)
	/Users/moshe/xud-simnet/go/src/github.com/ltcsuite/ltcd/blockchain/chainio.go:1229 +0x3f
github.com/ltcsuite/ltcd/blockchain.dbFetchHeaderByHeight(0x17f7440, 0xc4200d01b0, 0x0, 0xc420184690, 0x1, 0x1)
	/Users/moshe/xud-simnet/go/src/github.com/ltcsuite/ltcd/blockchain/chainio.go:1251 +0x8f
github.com/ltcsuite/ltcd/blockchain.(*BlockChain).initChainState.func1(0x17f7440, 0xc4200d01b0, 0xc4200d01b0, 0x0)
	/Users/moshe/xud-simnet/go/src/github.com/ltcsuite/ltcd/blockchain/chainio.go:1158 +0x37d
github.com/ltcsuite/ltcd/database/ffldb.(*db).View(0xc4200c6300, 0xc4204fa000, 0x0, 0x0)
	/Users/moshe/xud-simnet/go/src/github.com/ltcsuite/ltcd/database/ffldb/db.go:1912 +0x9b
github.com/ltcsuite/ltcd/blockchain.(*BlockChain).initChainState(0xc42047e780, 0xc4200c22a0, 0x3)
	/Users/moshe/xud-simnet/go/src/github.com/ltcsuite/ltcd/blockchain/chainio.go:1133 +0x99
github.com/ltcsuite/ltcd/blockchain.New(0xc4203f6180, 0xc4203f6180, 0x0, 0x0)
	/Users/moshe/xud-simnet/go/src/github.com/ltcsuite/ltcd/blockchain/chain.go:1578 +0x528
main.newServer(0xc4200b26c0, 0x1, 0x1, 0x17f3ec0, 0xc4200c6300, 0x1ab2ec0, 0xc4200b3320, 0xc4204d0b20, 0xc4204d0b00)
	/Users/moshe/xud-simnet/go/src/github.com/ltcsuite/ltcd/server.go:2477 +0x8ab
main.ltcdMain(0x0, 0x0, 0x0)
	/Users/moshe/xud-simnet/go/src/github.com/ltcsuite/ltcd/btcd.go:141 +0x672
main.main()
	/Users/moshe/xud-simnet/go/src/github.com/ltcsuite/ltcd/btcd.go:322 +0xd0
```

**Comment by offerm** [comment]
please add --debuglevel=trace  and try again. 

Looks to me you have something on these ports already.
